<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4964d14e-7290-4bba-9424-4f525a50caad</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.100.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Supabase" Version="1.1.1" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
  </ItemGroup>

</Project>
